/*
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

def fibonacci(x: Int, y: Int): Stream[Int] = {
  x #:: fibonacci(y, x + y)
}

fibonacci(1, 2).takeWhile(n => n <= 4000000).filter(n => n % 2 == 0).sum //=> res0: Int = 4613732
